name: giru
channels:
  - conda-forge
dependencies:
  - python=3.10
  - termcolor
  - python-dotenv
  - loguru
  - ffmpeg
  #- libiconv
  - flask
  - black
  - pip
  - pip:
      - yt-dlp
      - discord.py[voice]>=2.2.0
      - pynacl
