name: GiruBot
channels:
  - conda-forge
dependencies:
  - python
  - termcolor
  - python-dotenv
  - loguru
  - ffmpeg
  - flask
  - libffi
  - black
  - pip
  - pip:
      - yt-dlp
      - PyNaCl
      - discord.py[voice]
