name: giru
channels:
  - conda-forge
dependencies:
  - python=3.10
  - termcolor
  - python-dotenv
  - loguru
  - ffmpeg
  - flask
  - anaconda::libffi
  - black
  - pip
  - pip:
      - yt-dlp
      - PyNaCl
      - discord.py[voice]
