name: commands-progress


jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: count-checked
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          grep -c '\- \[ \]' README.md
  
    - name: count-total
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          grep -c '\- \[[ X]\]' README.md