name: commands-progress

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: print-working-dir
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          pwd

      - name: ls
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          ls

      - name: count-checked
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          grep -c '\- \[ \]' README.md

      - name: count-total
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          grep -c '\- \[[ X]\]' README.md
