name: commands-progress

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: count-checked
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          echo "COUNT_CHECKED=$(grep -c '\- \[X\]' README.md)" >> $GITHUB_ENV

      - name: count-total
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          echo "COUNT_TOTAL=$(grep -c '\- \[[ X]\]' README.md)" >> $GITHUB_ENV

      - name: print stats
        working-directory: ${{github.workspace}}
        shell: bash
        run: echo "${{ env.COUNT_CHECKED }} / ${{ env.COUNT_TOTAL }}"
